// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/PicoTools/pico/internal/ent/agent"
	"github.com/PicoTools/pico/internal/ent/listener"
	"github.com/PicoTools/pico/internal/types"
	"github.com/PicoTools/pico/pkg/shared"
)

// Agent is the model entity for the Agent schema.
type Agent struct {
	config `json:"-"`
	// ID of the ent.
	// agent ID
	ID uint32 `json:"id,omitempty"`
	// Time when entity was created
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Time when entity was updated
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Time when entity was soft-deleted
	DeletedAt time.Time `json:"deleted_at,omitempty"`
	// linked listener ID
	ListenerID int64 `json:"listener_id,omitempty"`
	// external IP address of agent
	ExtIP types.Inet `json:"ext_ip,omitempty"`
	// internal IP address of agent
	IntIP types.Inet `json:"int_ip,omitempty"`
	// type of operating system
	Os shared.AgentOs `json:"os,omitempty"`
	// metadata of operating system
	OsMeta string `json:"os_meta,omitempty"`
	// hostname of machine, on which agent deployed
	Hostname string `json:"hostname,omitempty"`
	// username of agent's process
	Username string `json:"username,omitempty"`
	// domain of machine, on which agent deployed
	Domain string `json:"domain,omitempty"`
	// is agent process is privileged
	Privileged bool `json:"privileged,omitempty"`
	// name of agent process
	ProcessName string `json:"process_name,omitempty"`
	// process ID of agent
	Pid int64 `json:"pid,omitempty"`
	// architecture of agent process
	Arch shared.AgentArch `json:"arch,omitempty"`
	// sleep value of agent
	Sleep uint32 `json:"sleep,omitempty"`
	// jitter value of sleep
	Jitter uint8 `json:"jitter,omitempty"`
	// first checkout timestamp
	First time.Time `json:"first,omitempty"`
	// last activity of listener
	Last time.Time `json:"last,omitempty"`
	// capabilities of agent
	Caps uint32 `json:"caps,omitempty"`
	// note of agent
	Note string `json:"note,omitempty"`
	// color of entity
	Color uint32 `json:"color,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AgentQuery when eager-loading is set.
	Edges        AgentEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AgentEdges holds the relations/edges for other nodes in the graph.
type AgentEdges struct {
	// Listener holds the value of the listener edge.
	Listener *Listener `json:"listener,omitempty"`
	// Command holds the value of the command edge.
	Command []*Command `json:"command,omitempty"`
	// Task holds the value of the task edge.
	Task []*Task `json:"task,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// ListenerOrErr returns the Listener value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AgentEdges) ListenerOrErr() (*Listener, error) {
	if e.Listener != nil {
		return e.Listener, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: listener.Label}
	}
	return nil, &NotLoadedError{edge: "listener"}
}

// CommandOrErr returns the Command value or an error if the edge
// was not loaded in eager-loading.
func (e AgentEdges) CommandOrErr() ([]*Command, error) {
	if e.loadedTypes[1] {
		return e.Command, nil
	}
	return nil, &NotLoadedError{edge: "command"}
}

// TaskOrErr returns the Task value or an error if the edge
// was not loaded in eager-loading.
func (e AgentEdges) TaskOrErr() ([]*Task, error) {
	if e.loadedTypes[2] {
		return e.Task, nil
	}
	return nil, &NotLoadedError{edge: "task"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Agent) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case agent.FieldArch:
			values[i] = new(shared.AgentArch)
		case agent.FieldOs:
			values[i] = new(shared.AgentOs)
		case agent.FieldPrivileged:
			values[i] = new(sql.NullBool)
		case agent.FieldID, agent.FieldListenerID, agent.FieldPid, agent.FieldSleep, agent.FieldJitter, agent.FieldCaps, agent.FieldColor:
			values[i] = new(sql.NullInt64)
		case agent.FieldOsMeta, agent.FieldHostname, agent.FieldUsername, agent.FieldDomain, agent.FieldProcessName, agent.FieldNote:
			values[i] = new(sql.NullString)
		case agent.FieldCreatedAt, agent.FieldUpdatedAt, agent.FieldDeletedAt, agent.FieldFirst, agent.FieldLast:
			values[i] = new(sql.NullTime)
		case agent.FieldExtIP, agent.FieldIntIP:
			values[i] = new(types.Inet)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Agent fields.
func (a *Agent) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case agent.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			a.ID = uint32(value.Int64)
		case agent.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				a.CreatedAt = value.Time
			}
		case agent.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				a.UpdatedAt = value.Time
			}
		case agent.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				a.DeletedAt = value.Time
			}
		case agent.FieldListenerID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field listener_id", values[i])
			} else if value.Valid {
				a.ListenerID = value.Int64
			}
		case agent.FieldExtIP:
			if value, ok := values[i].(*types.Inet); !ok {
				return fmt.Errorf("unexpected type %T for field ext_ip", values[i])
			} else if value != nil {
				a.ExtIP = *value
			}
		case agent.FieldIntIP:
			if value, ok := values[i].(*types.Inet); !ok {
				return fmt.Errorf("unexpected type %T for field int_ip", values[i])
			} else if value != nil {
				a.IntIP = *value
			}
		case agent.FieldOs:
			if value, ok := values[i].(*shared.AgentOs); !ok {
				return fmt.Errorf("unexpected type %T for field os", values[i])
			} else if value != nil {
				a.Os = *value
			}
		case agent.FieldOsMeta:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field os_meta", values[i])
			} else if value.Valid {
				a.OsMeta = value.String
			}
		case agent.FieldHostname:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field hostname", values[i])
			} else if value.Valid {
				a.Hostname = value.String
			}
		case agent.FieldUsername:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field username", values[i])
			} else if value.Valid {
				a.Username = value.String
			}
		case agent.FieldDomain:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field domain", values[i])
			} else if value.Valid {
				a.Domain = value.String
			}
		case agent.FieldPrivileged:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field privileged", values[i])
			} else if value.Valid {
				a.Privileged = value.Bool
			}
		case agent.FieldProcessName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field process_name", values[i])
			} else if value.Valid {
				a.ProcessName = value.String
			}
		case agent.FieldPid:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field pid", values[i])
			} else if value.Valid {
				a.Pid = value.Int64
			}
		case agent.FieldArch:
			if value, ok := values[i].(*shared.AgentArch); !ok {
				return fmt.Errorf("unexpected type %T for field arch", values[i])
			} else if value != nil {
				a.Arch = *value
			}
		case agent.FieldSleep:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sleep", values[i])
			} else if value.Valid {
				a.Sleep = uint32(value.Int64)
			}
		case agent.FieldJitter:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field jitter", values[i])
			} else if value.Valid {
				a.Jitter = uint8(value.Int64)
			}
		case agent.FieldFirst:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field first", values[i])
			} else if value.Valid {
				a.First = value.Time
			}
		case agent.FieldLast:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last", values[i])
			} else if value.Valid {
				a.Last = value.Time
			}
		case agent.FieldCaps:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field caps", values[i])
			} else if value.Valid {
				a.Caps = uint32(value.Int64)
			}
		case agent.FieldNote:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field note", values[i])
			} else if value.Valid {
				a.Note = value.String
			}
		case agent.FieldColor:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field color", values[i])
			} else if value.Valid {
				a.Color = uint32(value.Int64)
			}
		default:
			a.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Agent.
// This includes values selected through modifiers, order, etc.
func (a *Agent) Value(name string) (ent.Value, error) {
	return a.selectValues.Get(name)
}

// QueryListener queries the "listener" edge of the Agent entity.
func (a *Agent) QueryListener() *ListenerQuery {
	return NewAgentClient(a.config).QueryListener(a)
}

// QueryCommand queries the "command" edge of the Agent entity.
func (a *Agent) QueryCommand() *CommandQuery {
	return NewAgentClient(a.config).QueryCommand(a)
}

// QueryTask queries the "task" edge of the Agent entity.
func (a *Agent) QueryTask() *TaskQuery {
	return NewAgentClient(a.config).QueryTask(a)
}

// Update returns a builder for updating this Agent.
// Note that you need to call Agent.Unwrap() before calling this method if this Agent
// was returned from a transaction, and the transaction was committed or rolled back.
func (a *Agent) Update() *AgentUpdateOne {
	return NewAgentClient(a.config).UpdateOne(a)
}

// Unwrap unwraps the Agent entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (a *Agent) Unwrap() *Agent {
	_tx, ok := a.config.driver.(*txDriver)
	if !ok {
		panic("ent: Agent is not a transactional entity")
	}
	a.config.driver = _tx.drv
	return a
}

// String implements the fmt.Stringer.
func (a *Agent) String() string {
	var builder strings.Builder
	builder.WriteString("Agent(")
	builder.WriteString(fmt.Sprintf("id=%v, ", a.ID))
	builder.WriteString("created_at=")
	builder.WriteString(a.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(a.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("deleted_at=")
	builder.WriteString(a.DeletedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("listener_id=")
	builder.WriteString(fmt.Sprintf("%v", a.ListenerID))
	builder.WriteString(", ")
	builder.WriteString("ext_ip=")
	builder.WriteString(fmt.Sprintf("%v", a.ExtIP))
	builder.WriteString(", ")
	builder.WriteString("int_ip=")
	builder.WriteString(fmt.Sprintf("%v", a.IntIP))
	builder.WriteString(", ")
	builder.WriteString("os=")
	builder.WriteString(fmt.Sprintf("%v", a.Os))
	builder.WriteString(", ")
	builder.WriteString("os_meta=")
	builder.WriteString(a.OsMeta)
	builder.WriteString(", ")
	builder.WriteString("hostname=")
	builder.WriteString(a.Hostname)
	builder.WriteString(", ")
	builder.WriteString("username=")
	builder.WriteString(a.Username)
	builder.WriteString(", ")
	builder.WriteString("domain=")
	builder.WriteString(a.Domain)
	builder.WriteString(", ")
	builder.WriteString("privileged=")
	builder.WriteString(fmt.Sprintf("%v", a.Privileged))
	builder.WriteString(", ")
	builder.WriteString("process_name=")
	builder.WriteString(a.ProcessName)
	builder.WriteString(", ")
	builder.WriteString("pid=")
	builder.WriteString(fmt.Sprintf("%v", a.Pid))
	builder.WriteString(", ")
	builder.WriteString("arch=")
	builder.WriteString(fmt.Sprintf("%v", a.Arch))
	builder.WriteString(", ")
	builder.WriteString("sleep=")
	builder.WriteString(fmt.Sprintf("%v", a.Sleep))
	builder.WriteString(", ")
	builder.WriteString("jitter=")
	builder.WriteString(fmt.Sprintf("%v", a.Jitter))
	builder.WriteString(", ")
	builder.WriteString("first=")
	builder.WriteString(a.First.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("last=")
	builder.WriteString(a.Last.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("caps=")
	builder.WriteString(fmt.Sprintf("%v", a.Caps))
	builder.WriteString(", ")
	builder.WriteString("note=")
	builder.WriteString(a.Note)
	builder.WriteString(", ")
	builder.WriteString("color=")
	builder.WriteString(fmt.Sprintf("%v", a.Color))
	builder.WriteByte(')')
	return builder.String()
}

// Agents is a parsable slice of Agent.
type Agents []*Agent
