// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/PicoTools/pico-shared/shared"
	"github.com/PicoTools/pico/internal/ent/ant"
	"github.com/PicoTools/pico/internal/ent/command"
	"github.com/PicoTools/pico/internal/ent/listener"
	"github.com/PicoTools/pico/internal/ent/predicate"
	"github.com/PicoTools/pico/internal/ent/task"
	"github.com/PicoTools/pico/internal/types"
)

// AntUpdate is the builder for updating Ant entities.
type AntUpdate struct {
	config
	hooks    []Hook
	mutation *AntMutation
}

// Where appends a list predicates to the AntUpdate builder.
func (au *AntUpdate) Where(ps ...predicate.Ant) *AntUpdate {
	au.mutation.Where(ps...)
	return au
}

// SetUpdatedAt sets the "updated_at" field.
func (au *AntUpdate) SetUpdatedAt(t time.Time) *AntUpdate {
	au.mutation.SetUpdatedAt(t)
	return au
}

// SetDeletedAt sets the "deleted_at" field.
func (au *AntUpdate) SetDeletedAt(t time.Time) *AntUpdate {
	au.mutation.SetDeletedAt(t)
	return au
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (au *AntUpdate) SetNillableDeletedAt(t *time.Time) *AntUpdate {
	if t != nil {
		au.SetDeletedAt(*t)
	}
	return au
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (au *AntUpdate) ClearDeletedAt() *AntUpdate {
	au.mutation.ClearDeletedAt()
	return au
}

// SetListenerID sets the "listener_id" field.
func (au *AntUpdate) SetListenerID(i int64) *AntUpdate {
	au.mutation.SetListenerID(i)
	return au
}

// SetNillableListenerID sets the "listener_id" field if the given value is not nil.
func (au *AntUpdate) SetNillableListenerID(i *int64) *AntUpdate {
	if i != nil {
		au.SetListenerID(*i)
	}
	return au
}

// SetExtIP sets the "ext_ip" field.
func (au *AntUpdate) SetExtIP(t types.Inet) *AntUpdate {
	au.mutation.SetExtIP(t)
	return au
}

// SetNillableExtIP sets the "ext_ip" field if the given value is not nil.
func (au *AntUpdate) SetNillableExtIP(t *types.Inet) *AntUpdate {
	if t != nil {
		au.SetExtIP(*t)
	}
	return au
}

// ClearExtIP clears the value of the "ext_ip" field.
func (au *AntUpdate) ClearExtIP() *AntUpdate {
	au.mutation.ClearExtIP()
	return au
}

// SetIntIP sets the "int_ip" field.
func (au *AntUpdate) SetIntIP(t types.Inet) *AntUpdate {
	au.mutation.SetIntIP(t)
	return au
}

// SetNillableIntIP sets the "int_ip" field if the given value is not nil.
func (au *AntUpdate) SetNillableIntIP(t *types.Inet) *AntUpdate {
	if t != nil {
		au.SetIntIP(*t)
	}
	return au
}

// ClearIntIP clears the value of the "int_ip" field.
func (au *AntUpdate) ClearIntIP() *AntUpdate {
	au.mutation.ClearIntIP()
	return au
}

// SetOs sets the "os" field.
func (au *AntUpdate) SetOs(so shared.AntOs) *AntUpdate {
	au.mutation.SetOs(so)
	return au
}

// SetNillableOs sets the "os" field if the given value is not nil.
func (au *AntUpdate) SetNillableOs(so *shared.AntOs) *AntUpdate {
	if so != nil {
		au.SetOs(*so)
	}
	return au
}

// SetOsMeta sets the "os_meta" field.
func (au *AntUpdate) SetOsMeta(s string) *AntUpdate {
	au.mutation.SetOsMeta(s)
	return au
}

// SetNillableOsMeta sets the "os_meta" field if the given value is not nil.
func (au *AntUpdate) SetNillableOsMeta(s *string) *AntUpdate {
	if s != nil {
		au.SetOsMeta(*s)
	}
	return au
}

// ClearOsMeta clears the value of the "os_meta" field.
func (au *AntUpdate) ClearOsMeta() *AntUpdate {
	au.mutation.ClearOsMeta()
	return au
}

// SetHostname sets the "hostname" field.
func (au *AntUpdate) SetHostname(s string) *AntUpdate {
	au.mutation.SetHostname(s)
	return au
}

// SetNillableHostname sets the "hostname" field if the given value is not nil.
func (au *AntUpdate) SetNillableHostname(s *string) *AntUpdate {
	if s != nil {
		au.SetHostname(*s)
	}
	return au
}

// ClearHostname clears the value of the "hostname" field.
func (au *AntUpdate) ClearHostname() *AntUpdate {
	au.mutation.ClearHostname()
	return au
}

// SetUsername sets the "username" field.
func (au *AntUpdate) SetUsername(s string) *AntUpdate {
	au.mutation.SetUsername(s)
	return au
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (au *AntUpdate) SetNillableUsername(s *string) *AntUpdate {
	if s != nil {
		au.SetUsername(*s)
	}
	return au
}

// ClearUsername clears the value of the "username" field.
func (au *AntUpdate) ClearUsername() *AntUpdate {
	au.mutation.ClearUsername()
	return au
}

// SetDomain sets the "domain" field.
func (au *AntUpdate) SetDomain(s string) *AntUpdate {
	au.mutation.SetDomain(s)
	return au
}

// SetNillableDomain sets the "domain" field if the given value is not nil.
func (au *AntUpdate) SetNillableDomain(s *string) *AntUpdate {
	if s != nil {
		au.SetDomain(*s)
	}
	return au
}

// ClearDomain clears the value of the "domain" field.
func (au *AntUpdate) ClearDomain() *AntUpdate {
	au.mutation.ClearDomain()
	return au
}

// SetPrivileged sets the "privileged" field.
func (au *AntUpdate) SetPrivileged(b bool) *AntUpdate {
	au.mutation.SetPrivileged(b)
	return au
}

// SetNillablePrivileged sets the "privileged" field if the given value is not nil.
func (au *AntUpdate) SetNillablePrivileged(b *bool) *AntUpdate {
	if b != nil {
		au.SetPrivileged(*b)
	}
	return au
}

// ClearPrivileged clears the value of the "privileged" field.
func (au *AntUpdate) ClearPrivileged() *AntUpdate {
	au.mutation.ClearPrivileged()
	return au
}

// SetProcessName sets the "process_name" field.
func (au *AntUpdate) SetProcessName(s string) *AntUpdate {
	au.mutation.SetProcessName(s)
	return au
}

// SetNillableProcessName sets the "process_name" field if the given value is not nil.
func (au *AntUpdate) SetNillableProcessName(s *string) *AntUpdate {
	if s != nil {
		au.SetProcessName(*s)
	}
	return au
}

// ClearProcessName clears the value of the "process_name" field.
func (au *AntUpdate) ClearProcessName() *AntUpdate {
	au.mutation.ClearProcessName()
	return au
}

// SetPid sets the "pid" field.
func (au *AntUpdate) SetPid(i int64) *AntUpdate {
	au.mutation.ResetPid()
	au.mutation.SetPid(i)
	return au
}

// SetNillablePid sets the "pid" field if the given value is not nil.
func (au *AntUpdate) SetNillablePid(i *int64) *AntUpdate {
	if i != nil {
		au.SetPid(*i)
	}
	return au
}

// AddPid adds i to the "pid" field.
func (au *AntUpdate) AddPid(i int64) *AntUpdate {
	au.mutation.AddPid(i)
	return au
}

// ClearPid clears the value of the "pid" field.
func (au *AntUpdate) ClearPid() *AntUpdate {
	au.mutation.ClearPid()
	return au
}

// SetArch sets the "arch" field.
func (au *AntUpdate) SetArch(sa shared.AntArch) *AntUpdate {
	au.mutation.SetArch(sa)
	return au
}

// SetNillableArch sets the "arch" field if the given value is not nil.
func (au *AntUpdate) SetNillableArch(sa *shared.AntArch) *AntUpdate {
	if sa != nil {
		au.SetArch(*sa)
	}
	return au
}

// SetSleep sets the "sleep" field.
func (au *AntUpdate) SetSleep(u uint32) *AntUpdate {
	au.mutation.ResetSleep()
	au.mutation.SetSleep(u)
	return au
}

// SetNillableSleep sets the "sleep" field if the given value is not nil.
func (au *AntUpdate) SetNillableSleep(u *uint32) *AntUpdate {
	if u != nil {
		au.SetSleep(*u)
	}
	return au
}

// AddSleep adds u to the "sleep" field.
func (au *AntUpdate) AddSleep(u int32) *AntUpdate {
	au.mutation.AddSleep(u)
	return au
}

// SetJitter sets the "jitter" field.
func (au *AntUpdate) SetJitter(u uint8) *AntUpdate {
	au.mutation.ResetJitter()
	au.mutation.SetJitter(u)
	return au
}

// SetNillableJitter sets the "jitter" field if the given value is not nil.
func (au *AntUpdate) SetNillableJitter(u *uint8) *AntUpdate {
	if u != nil {
		au.SetJitter(*u)
	}
	return au
}

// AddJitter adds u to the "jitter" field.
func (au *AntUpdate) AddJitter(u int8) *AntUpdate {
	au.mutation.AddJitter(u)
	return au
}

// SetFirst sets the "first" field.
func (au *AntUpdate) SetFirst(t time.Time) *AntUpdate {
	au.mutation.SetFirst(t)
	return au
}

// SetNillableFirst sets the "first" field if the given value is not nil.
func (au *AntUpdate) SetNillableFirst(t *time.Time) *AntUpdate {
	if t != nil {
		au.SetFirst(*t)
	}
	return au
}

// SetLast sets the "last" field.
func (au *AntUpdate) SetLast(t time.Time) *AntUpdate {
	au.mutation.SetLast(t)
	return au
}

// SetNillableLast sets the "last" field if the given value is not nil.
func (au *AntUpdate) SetNillableLast(t *time.Time) *AntUpdate {
	if t != nil {
		au.SetLast(*t)
	}
	return au
}

// SetCaps sets the "caps" field.
func (au *AntUpdate) SetCaps(u uint32) *AntUpdate {
	au.mutation.ResetCaps()
	au.mutation.SetCaps(u)
	return au
}

// SetNillableCaps sets the "caps" field if the given value is not nil.
func (au *AntUpdate) SetNillableCaps(u *uint32) *AntUpdate {
	if u != nil {
		au.SetCaps(*u)
	}
	return au
}

// AddCaps adds u to the "caps" field.
func (au *AntUpdate) AddCaps(u int32) *AntUpdate {
	au.mutation.AddCaps(u)
	return au
}

// SetNote sets the "note" field.
func (au *AntUpdate) SetNote(s string) *AntUpdate {
	au.mutation.SetNote(s)
	return au
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (au *AntUpdate) SetNillableNote(s *string) *AntUpdate {
	if s != nil {
		au.SetNote(*s)
	}
	return au
}

// ClearNote clears the value of the "note" field.
func (au *AntUpdate) ClearNote() *AntUpdate {
	au.mutation.ClearNote()
	return au
}

// SetColor sets the "color" field.
func (au *AntUpdate) SetColor(u uint32) *AntUpdate {
	au.mutation.ResetColor()
	au.mutation.SetColor(u)
	return au
}

// SetNillableColor sets the "color" field if the given value is not nil.
func (au *AntUpdate) SetNillableColor(u *uint32) *AntUpdate {
	if u != nil {
		au.SetColor(*u)
	}
	return au
}

// AddColor adds u to the "color" field.
func (au *AntUpdate) AddColor(u int32) *AntUpdate {
	au.mutation.AddColor(u)
	return au
}

// SetListener sets the "listener" edge to the Listener entity.
func (au *AntUpdate) SetListener(l *Listener) *AntUpdate {
	return au.SetListenerID(l.ID)
}

// AddCommandIDs adds the "command" edge to the Command entity by IDs.
func (au *AntUpdate) AddCommandIDs(ids ...int64) *AntUpdate {
	au.mutation.AddCommandIDs(ids...)
	return au
}

// AddCommand adds the "command" edges to the Command entity.
func (au *AntUpdate) AddCommand(c ...*Command) *AntUpdate {
	ids := make([]int64, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return au.AddCommandIDs(ids...)
}

// AddTaskIDs adds the "task" edge to the Task entity by IDs.
func (au *AntUpdate) AddTaskIDs(ids ...int64) *AntUpdate {
	au.mutation.AddTaskIDs(ids...)
	return au
}

// AddTask adds the "task" edges to the Task entity.
func (au *AntUpdate) AddTask(t ...*Task) *AntUpdate {
	ids := make([]int64, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return au.AddTaskIDs(ids...)
}

// Mutation returns the AntMutation object of the builder.
func (au *AntUpdate) Mutation() *AntMutation {
	return au.mutation
}

// ClearListener clears the "listener" edge to the Listener entity.
func (au *AntUpdate) ClearListener() *AntUpdate {
	au.mutation.ClearListener()
	return au
}

// ClearCommand clears all "command" edges to the Command entity.
func (au *AntUpdate) ClearCommand() *AntUpdate {
	au.mutation.ClearCommand()
	return au
}

// RemoveCommandIDs removes the "command" edge to Command entities by IDs.
func (au *AntUpdate) RemoveCommandIDs(ids ...int64) *AntUpdate {
	au.mutation.RemoveCommandIDs(ids...)
	return au
}

// RemoveCommand removes "command" edges to Command entities.
func (au *AntUpdate) RemoveCommand(c ...*Command) *AntUpdate {
	ids := make([]int64, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return au.RemoveCommandIDs(ids...)
}

// ClearTask clears all "task" edges to the Task entity.
func (au *AntUpdate) ClearTask() *AntUpdate {
	au.mutation.ClearTask()
	return au
}

// RemoveTaskIDs removes the "task" edge to Task entities by IDs.
func (au *AntUpdate) RemoveTaskIDs(ids ...int64) *AntUpdate {
	au.mutation.RemoveTaskIDs(ids...)
	return au
}

// RemoveTask removes "task" edges to Task entities.
func (au *AntUpdate) RemoveTask(t ...*Task) *AntUpdate {
	ids := make([]int64, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return au.RemoveTaskIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (au *AntUpdate) Save(ctx context.Context) (int, error) {
	if err := au.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, au.sqlSave, au.mutation, au.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (au *AntUpdate) SaveX(ctx context.Context) int {
	affected, err := au.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (au *AntUpdate) Exec(ctx context.Context) error {
	_, err := au.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (au *AntUpdate) ExecX(ctx context.Context) {
	if err := au.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (au *AntUpdate) defaults() error {
	if _, ok := au.mutation.UpdatedAt(); !ok {
		if ant.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized ant.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := ant.UpdateDefaultUpdatedAt()
		au.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (au *AntUpdate) check() error {
	if v, ok := au.mutation.ExtIP(); ok {
		if err := ant.ExtIPValidator(v.String()); err != nil {
			return &ValidationError{Name: "ext_ip", err: fmt.Errorf(`ent: validator failed for field "Ant.ext_ip": %w`, err)}
		}
	}
	if v, ok := au.mutation.IntIP(); ok {
		if err := ant.IntIPValidator(v.String()); err != nil {
			return &ValidationError{Name: "int_ip", err: fmt.Errorf(`ent: validator failed for field "Ant.int_ip": %w`, err)}
		}
	}
	if v, ok := au.mutation.Os(); ok {
		if err := ant.OsValidator(v); err != nil {
			return &ValidationError{Name: "os", err: fmt.Errorf(`ent: validator failed for field "Ant.os": %w`, err)}
		}
	}
	if v, ok := au.mutation.OsMeta(); ok {
		if err := ant.OsMetaValidator(v); err != nil {
			return &ValidationError{Name: "os_meta", err: fmt.Errorf(`ent: validator failed for field "Ant.os_meta": %w`, err)}
		}
	}
	if v, ok := au.mutation.Hostname(); ok {
		if err := ant.HostnameValidator(v); err != nil {
			return &ValidationError{Name: "hostname", err: fmt.Errorf(`ent: validator failed for field "Ant.hostname": %w`, err)}
		}
	}
	if v, ok := au.mutation.Username(); ok {
		if err := ant.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "Ant.username": %w`, err)}
		}
	}
	if v, ok := au.mutation.Domain(); ok {
		if err := ant.DomainValidator(v); err != nil {
			return &ValidationError{Name: "domain", err: fmt.Errorf(`ent: validator failed for field "Ant.domain": %w`, err)}
		}
	}
	if v, ok := au.mutation.ProcessName(); ok {
		if err := ant.ProcessNameValidator(v); err != nil {
			return &ValidationError{Name: "process_name", err: fmt.Errorf(`ent: validator failed for field "Ant.process_name": %w`, err)}
		}
	}
	if v, ok := au.mutation.Arch(); ok {
		if err := ant.ArchValidator(v); err != nil {
			return &ValidationError{Name: "arch", err: fmt.Errorf(`ent: validator failed for field "Ant.arch": %w`, err)}
		}
	}
	if v, ok := au.mutation.Note(); ok {
		if err := ant.NoteValidator(v); err != nil {
			return &ValidationError{Name: "note", err: fmt.Errorf(`ent: validator failed for field "Ant.note": %w`, err)}
		}
	}
	if au.mutation.ListenerCleared() && len(au.mutation.ListenerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Ant.listener"`)
	}
	return nil
}

func (au *AntUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := au.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(ant.Table, ant.Columns, sqlgraph.NewFieldSpec(ant.FieldID, field.TypeUint32))
	if ps := au.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := au.mutation.UpdatedAt(); ok {
		_spec.SetField(ant.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := au.mutation.DeletedAt(); ok {
		_spec.SetField(ant.FieldDeletedAt, field.TypeTime, value)
	}
	if au.mutation.DeletedAtCleared() {
		_spec.ClearField(ant.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := au.mutation.ExtIP(); ok {
		_spec.SetField(ant.FieldExtIP, field.TypeString, value)
	}
	if au.mutation.ExtIPCleared() {
		_spec.ClearField(ant.FieldExtIP, field.TypeString)
	}
	if value, ok := au.mutation.IntIP(); ok {
		_spec.SetField(ant.FieldIntIP, field.TypeString, value)
	}
	if au.mutation.IntIPCleared() {
		_spec.ClearField(ant.FieldIntIP, field.TypeString)
	}
	if value, ok := au.mutation.Os(); ok {
		_spec.SetField(ant.FieldOs, field.TypeEnum, value)
	}
	if value, ok := au.mutation.OsMeta(); ok {
		_spec.SetField(ant.FieldOsMeta, field.TypeString, value)
	}
	if au.mutation.OsMetaCleared() {
		_spec.ClearField(ant.FieldOsMeta, field.TypeString)
	}
	if value, ok := au.mutation.Hostname(); ok {
		_spec.SetField(ant.FieldHostname, field.TypeString, value)
	}
	if au.mutation.HostnameCleared() {
		_spec.ClearField(ant.FieldHostname, field.TypeString)
	}
	if value, ok := au.mutation.Username(); ok {
		_spec.SetField(ant.FieldUsername, field.TypeString, value)
	}
	if au.mutation.UsernameCleared() {
		_spec.ClearField(ant.FieldUsername, field.TypeString)
	}
	if value, ok := au.mutation.Domain(); ok {
		_spec.SetField(ant.FieldDomain, field.TypeString, value)
	}
	if au.mutation.DomainCleared() {
		_spec.ClearField(ant.FieldDomain, field.TypeString)
	}
	if value, ok := au.mutation.Privileged(); ok {
		_spec.SetField(ant.FieldPrivileged, field.TypeBool, value)
	}
	if au.mutation.PrivilegedCleared() {
		_spec.ClearField(ant.FieldPrivileged, field.TypeBool)
	}
	if value, ok := au.mutation.ProcessName(); ok {
		_spec.SetField(ant.FieldProcessName, field.TypeString, value)
	}
	if au.mutation.ProcessNameCleared() {
		_spec.ClearField(ant.FieldProcessName, field.TypeString)
	}
	if value, ok := au.mutation.Pid(); ok {
		_spec.SetField(ant.FieldPid, field.TypeInt64, value)
	}
	if value, ok := au.mutation.AddedPid(); ok {
		_spec.AddField(ant.FieldPid, field.TypeInt64, value)
	}
	if au.mutation.PidCleared() {
		_spec.ClearField(ant.FieldPid, field.TypeInt64)
	}
	if value, ok := au.mutation.Arch(); ok {
		_spec.SetField(ant.FieldArch, field.TypeEnum, value)
	}
	if value, ok := au.mutation.Sleep(); ok {
		_spec.SetField(ant.FieldSleep, field.TypeUint32, value)
	}
	if value, ok := au.mutation.AddedSleep(); ok {
		_spec.AddField(ant.FieldSleep, field.TypeUint32, value)
	}
	if value, ok := au.mutation.Jitter(); ok {
		_spec.SetField(ant.FieldJitter, field.TypeUint8, value)
	}
	if value, ok := au.mutation.AddedJitter(); ok {
		_spec.AddField(ant.FieldJitter, field.TypeUint8, value)
	}
	if value, ok := au.mutation.First(); ok {
		_spec.SetField(ant.FieldFirst, field.TypeTime, value)
	}
	if value, ok := au.mutation.Last(); ok {
		_spec.SetField(ant.FieldLast, field.TypeTime, value)
	}
	if value, ok := au.mutation.Caps(); ok {
		_spec.SetField(ant.FieldCaps, field.TypeUint32, value)
	}
	if value, ok := au.mutation.AddedCaps(); ok {
		_spec.AddField(ant.FieldCaps, field.TypeUint32, value)
	}
	if value, ok := au.mutation.Note(); ok {
		_spec.SetField(ant.FieldNote, field.TypeString, value)
	}
	if au.mutation.NoteCleared() {
		_spec.ClearField(ant.FieldNote, field.TypeString)
	}
	if value, ok := au.mutation.Color(); ok {
		_spec.SetField(ant.FieldColor, field.TypeUint32, value)
	}
	if value, ok := au.mutation.AddedColor(); ok {
		_spec.AddField(ant.FieldColor, field.TypeUint32, value)
	}
	if au.mutation.ListenerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ant.ListenerTable,
			Columns: []string{ant.ListenerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(listener.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.ListenerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ant.ListenerTable,
			Columns: []string{ant.ListenerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(listener.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if au.mutation.CommandCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ant.CommandTable,
			Columns: []string{ant.CommandColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(command.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.RemovedCommandIDs(); len(nodes) > 0 && !au.mutation.CommandCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ant.CommandTable,
			Columns: []string{ant.CommandColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(command.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.CommandIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ant.CommandTable,
			Columns: []string{ant.CommandColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(command.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if au.mutation.TaskCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ant.TaskTable,
			Columns: []string{ant.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.RemovedTaskIDs(); len(nodes) > 0 && !au.mutation.TaskCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ant.TaskTable,
			Columns: []string{ant.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.TaskIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ant.TaskTable,
			Columns: []string{ant.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, au.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ant.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	au.mutation.done = true
	return n, nil
}

// AntUpdateOne is the builder for updating a single Ant entity.
type AntUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AntMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (auo *AntUpdateOne) SetUpdatedAt(t time.Time) *AntUpdateOne {
	auo.mutation.SetUpdatedAt(t)
	return auo
}

// SetDeletedAt sets the "deleted_at" field.
func (auo *AntUpdateOne) SetDeletedAt(t time.Time) *AntUpdateOne {
	auo.mutation.SetDeletedAt(t)
	return auo
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (auo *AntUpdateOne) SetNillableDeletedAt(t *time.Time) *AntUpdateOne {
	if t != nil {
		auo.SetDeletedAt(*t)
	}
	return auo
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (auo *AntUpdateOne) ClearDeletedAt() *AntUpdateOne {
	auo.mutation.ClearDeletedAt()
	return auo
}

// SetListenerID sets the "listener_id" field.
func (auo *AntUpdateOne) SetListenerID(i int64) *AntUpdateOne {
	auo.mutation.SetListenerID(i)
	return auo
}

// SetNillableListenerID sets the "listener_id" field if the given value is not nil.
func (auo *AntUpdateOne) SetNillableListenerID(i *int64) *AntUpdateOne {
	if i != nil {
		auo.SetListenerID(*i)
	}
	return auo
}

// SetExtIP sets the "ext_ip" field.
func (auo *AntUpdateOne) SetExtIP(t types.Inet) *AntUpdateOne {
	auo.mutation.SetExtIP(t)
	return auo
}

// SetNillableExtIP sets the "ext_ip" field if the given value is not nil.
func (auo *AntUpdateOne) SetNillableExtIP(t *types.Inet) *AntUpdateOne {
	if t != nil {
		auo.SetExtIP(*t)
	}
	return auo
}

// ClearExtIP clears the value of the "ext_ip" field.
func (auo *AntUpdateOne) ClearExtIP() *AntUpdateOne {
	auo.mutation.ClearExtIP()
	return auo
}

// SetIntIP sets the "int_ip" field.
func (auo *AntUpdateOne) SetIntIP(t types.Inet) *AntUpdateOne {
	auo.mutation.SetIntIP(t)
	return auo
}

// SetNillableIntIP sets the "int_ip" field if the given value is not nil.
func (auo *AntUpdateOne) SetNillableIntIP(t *types.Inet) *AntUpdateOne {
	if t != nil {
		auo.SetIntIP(*t)
	}
	return auo
}

// ClearIntIP clears the value of the "int_ip" field.
func (auo *AntUpdateOne) ClearIntIP() *AntUpdateOne {
	auo.mutation.ClearIntIP()
	return auo
}

// SetOs sets the "os" field.
func (auo *AntUpdateOne) SetOs(so shared.AntOs) *AntUpdateOne {
	auo.mutation.SetOs(so)
	return auo
}

// SetNillableOs sets the "os" field if the given value is not nil.
func (auo *AntUpdateOne) SetNillableOs(so *shared.AntOs) *AntUpdateOne {
	if so != nil {
		auo.SetOs(*so)
	}
	return auo
}

// SetOsMeta sets the "os_meta" field.
func (auo *AntUpdateOne) SetOsMeta(s string) *AntUpdateOne {
	auo.mutation.SetOsMeta(s)
	return auo
}

// SetNillableOsMeta sets the "os_meta" field if the given value is not nil.
func (auo *AntUpdateOne) SetNillableOsMeta(s *string) *AntUpdateOne {
	if s != nil {
		auo.SetOsMeta(*s)
	}
	return auo
}

// ClearOsMeta clears the value of the "os_meta" field.
func (auo *AntUpdateOne) ClearOsMeta() *AntUpdateOne {
	auo.mutation.ClearOsMeta()
	return auo
}

// SetHostname sets the "hostname" field.
func (auo *AntUpdateOne) SetHostname(s string) *AntUpdateOne {
	auo.mutation.SetHostname(s)
	return auo
}

// SetNillableHostname sets the "hostname" field if the given value is not nil.
func (auo *AntUpdateOne) SetNillableHostname(s *string) *AntUpdateOne {
	if s != nil {
		auo.SetHostname(*s)
	}
	return auo
}

// ClearHostname clears the value of the "hostname" field.
func (auo *AntUpdateOne) ClearHostname() *AntUpdateOne {
	auo.mutation.ClearHostname()
	return auo
}

// SetUsername sets the "username" field.
func (auo *AntUpdateOne) SetUsername(s string) *AntUpdateOne {
	auo.mutation.SetUsername(s)
	return auo
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (auo *AntUpdateOne) SetNillableUsername(s *string) *AntUpdateOne {
	if s != nil {
		auo.SetUsername(*s)
	}
	return auo
}

// ClearUsername clears the value of the "username" field.
func (auo *AntUpdateOne) ClearUsername() *AntUpdateOne {
	auo.mutation.ClearUsername()
	return auo
}

// SetDomain sets the "domain" field.
func (auo *AntUpdateOne) SetDomain(s string) *AntUpdateOne {
	auo.mutation.SetDomain(s)
	return auo
}

// SetNillableDomain sets the "domain" field if the given value is not nil.
func (auo *AntUpdateOne) SetNillableDomain(s *string) *AntUpdateOne {
	if s != nil {
		auo.SetDomain(*s)
	}
	return auo
}

// ClearDomain clears the value of the "domain" field.
func (auo *AntUpdateOne) ClearDomain() *AntUpdateOne {
	auo.mutation.ClearDomain()
	return auo
}

// SetPrivileged sets the "privileged" field.
func (auo *AntUpdateOne) SetPrivileged(b bool) *AntUpdateOne {
	auo.mutation.SetPrivileged(b)
	return auo
}

// SetNillablePrivileged sets the "privileged" field if the given value is not nil.
func (auo *AntUpdateOne) SetNillablePrivileged(b *bool) *AntUpdateOne {
	if b != nil {
		auo.SetPrivileged(*b)
	}
	return auo
}

// ClearPrivileged clears the value of the "privileged" field.
func (auo *AntUpdateOne) ClearPrivileged() *AntUpdateOne {
	auo.mutation.ClearPrivileged()
	return auo
}

// SetProcessName sets the "process_name" field.
func (auo *AntUpdateOne) SetProcessName(s string) *AntUpdateOne {
	auo.mutation.SetProcessName(s)
	return auo
}

// SetNillableProcessName sets the "process_name" field if the given value is not nil.
func (auo *AntUpdateOne) SetNillableProcessName(s *string) *AntUpdateOne {
	if s != nil {
		auo.SetProcessName(*s)
	}
	return auo
}

// ClearProcessName clears the value of the "process_name" field.
func (auo *AntUpdateOne) ClearProcessName() *AntUpdateOne {
	auo.mutation.ClearProcessName()
	return auo
}

// SetPid sets the "pid" field.
func (auo *AntUpdateOne) SetPid(i int64) *AntUpdateOne {
	auo.mutation.ResetPid()
	auo.mutation.SetPid(i)
	return auo
}

// SetNillablePid sets the "pid" field if the given value is not nil.
func (auo *AntUpdateOne) SetNillablePid(i *int64) *AntUpdateOne {
	if i != nil {
		auo.SetPid(*i)
	}
	return auo
}

// AddPid adds i to the "pid" field.
func (auo *AntUpdateOne) AddPid(i int64) *AntUpdateOne {
	auo.mutation.AddPid(i)
	return auo
}

// ClearPid clears the value of the "pid" field.
func (auo *AntUpdateOne) ClearPid() *AntUpdateOne {
	auo.mutation.ClearPid()
	return auo
}

// SetArch sets the "arch" field.
func (auo *AntUpdateOne) SetArch(sa shared.AntArch) *AntUpdateOne {
	auo.mutation.SetArch(sa)
	return auo
}

// SetNillableArch sets the "arch" field if the given value is not nil.
func (auo *AntUpdateOne) SetNillableArch(sa *shared.AntArch) *AntUpdateOne {
	if sa != nil {
		auo.SetArch(*sa)
	}
	return auo
}

// SetSleep sets the "sleep" field.
func (auo *AntUpdateOne) SetSleep(u uint32) *AntUpdateOne {
	auo.mutation.ResetSleep()
	auo.mutation.SetSleep(u)
	return auo
}

// SetNillableSleep sets the "sleep" field if the given value is not nil.
func (auo *AntUpdateOne) SetNillableSleep(u *uint32) *AntUpdateOne {
	if u != nil {
		auo.SetSleep(*u)
	}
	return auo
}

// AddSleep adds u to the "sleep" field.
func (auo *AntUpdateOne) AddSleep(u int32) *AntUpdateOne {
	auo.mutation.AddSleep(u)
	return auo
}

// SetJitter sets the "jitter" field.
func (auo *AntUpdateOne) SetJitter(u uint8) *AntUpdateOne {
	auo.mutation.ResetJitter()
	auo.mutation.SetJitter(u)
	return auo
}

// SetNillableJitter sets the "jitter" field if the given value is not nil.
func (auo *AntUpdateOne) SetNillableJitter(u *uint8) *AntUpdateOne {
	if u != nil {
		auo.SetJitter(*u)
	}
	return auo
}

// AddJitter adds u to the "jitter" field.
func (auo *AntUpdateOne) AddJitter(u int8) *AntUpdateOne {
	auo.mutation.AddJitter(u)
	return auo
}

// SetFirst sets the "first" field.
func (auo *AntUpdateOne) SetFirst(t time.Time) *AntUpdateOne {
	auo.mutation.SetFirst(t)
	return auo
}

// SetNillableFirst sets the "first" field if the given value is not nil.
func (auo *AntUpdateOne) SetNillableFirst(t *time.Time) *AntUpdateOne {
	if t != nil {
		auo.SetFirst(*t)
	}
	return auo
}

// SetLast sets the "last" field.
func (auo *AntUpdateOne) SetLast(t time.Time) *AntUpdateOne {
	auo.mutation.SetLast(t)
	return auo
}

// SetNillableLast sets the "last" field if the given value is not nil.
func (auo *AntUpdateOne) SetNillableLast(t *time.Time) *AntUpdateOne {
	if t != nil {
		auo.SetLast(*t)
	}
	return auo
}

// SetCaps sets the "caps" field.
func (auo *AntUpdateOne) SetCaps(u uint32) *AntUpdateOne {
	auo.mutation.ResetCaps()
	auo.mutation.SetCaps(u)
	return auo
}

// SetNillableCaps sets the "caps" field if the given value is not nil.
func (auo *AntUpdateOne) SetNillableCaps(u *uint32) *AntUpdateOne {
	if u != nil {
		auo.SetCaps(*u)
	}
	return auo
}

// AddCaps adds u to the "caps" field.
func (auo *AntUpdateOne) AddCaps(u int32) *AntUpdateOne {
	auo.mutation.AddCaps(u)
	return auo
}

// SetNote sets the "note" field.
func (auo *AntUpdateOne) SetNote(s string) *AntUpdateOne {
	auo.mutation.SetNote(s)
	return auo
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (auo *AntUpdateOne) SetNillableNote(s *string) *AntUpdateOne {
	if s != nil {
		auo.SetNote(*s)
	}
	return auo
}

// ClearNote clears the value of the "note" field.
func (auo *AntUpdateOne) ClearNote() *AntUpdateOne {
	auo.mutation.ClearNote()
	return auo
}

// SetColor sets the "color" field.
func (auo *AntUpdateOne) SetColor(u uint32) *AntUpdateOne {
	auo.mutation.ResetColor()
	auo.mutation.SetColor(u)
	return auo
}

// SetNillableColor sets the "color" field if the given value is not nil.
func (auo *AntUpdateOne) SetNillableColor(u *uint32) *AntUpdateOne {
	if u != nil {
		auo.SetColor(*u)
	}
	return auo
}

// AddColor adds u to the "color" field.
func (auo *AntUpdateOne) AddColor(u int32) *AntUpdateOne {
	auo.mutation.AddColor(u)
	return auo
}

// SetListener sets the "listener" edge to the Listener entity.
func (auo *AntUpdateOne) SetListener(l *Listener) *AntUpdateOne {
	return auo.SetListenerID(l.ID)
}

// AddCommandIDs adds the "command" edge to the Command entity by IDs.
func (auo *AntUpdateOne) AddCommandIDs(ids ...int64) *AntUpdateOne {
	auo.mutation.AddCommandIDs(ids...)
	return auo
}

// AddCommand adds the "command" edges to the Command entity.
func (auo *AntUpdateOne) AddCommand(c ...*Command) *AntUpdateOne {
	ids := make([]int64, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return auo.AddCommandIDs(ids...)
}

// AddTaskIDs adds the "task" edge to the Task entity by IDs.
func (auo *AntUpdateOne) AddTaskIDs(ids ...int64) *AntUpdateOne {
	auo.mutation.AddTaskIDs(ids...)
	return auo
}

// AddTask adds the "task" edges to the Task entity.
func (auo *AntUpdateOne) AddTask(t ...*Task) *AntUpdateOne {
	ids := make([]int64, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return auo.AddTaskIDs(ids...)
}

// Mutation returns the AntMutation object of the builder.
func (auo *AntUpdateOne) Mutation() *AntMutation {
	return auo.mutation
}

// ClearListener clears the "listener" edge to the Listener entity.
func (auo *AntUpdateOne) ClearListener() *AntUpdateOne {
	auo.mutation.ClearListener()
	return auo
}

// ClearCommand clears all "command" edges to the Command entity.
func (auo *AntUpdateOne) ClearCommand() *AntUpdateOne {
	auo.mutation.ClearCommand()
	return auo
}

// RemoveCommandIDs removes the "command" edge to Command entities by IDs.
func (auo *AntUpdateOne) RemoveCommandIDs(ids ...int64) *AntUpdateOne {
	auo.mutation.RemoveCommandIDs(ids...)
	return auo
}

// RemoveCommand removes "command" edges to Command entities.
func (auo *AntUpdateOne) RemoveCommand(c ...*Command) *AntUpdateOne {
	ids := make([]int64, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return auo.RemoveCommandIDs(ids...)
}

// ClearTask clears all "task" edges to the Task entity.
func (auo *AntUpdateOne) ClearTask() *AntUpdateOne {
	auo.mutation.ClearTask()
	return auo
}

// RemoveTaskIDs removes the "task" edge to Task entities by IDs.
func (auo *AntUpdateOne) RemoveTaskIDs(ids ...int64) *AntUpdateOne {
	auo.mutation.RemoveTaskIDs(ids...)
	return auo
}

// RemoveTask removes "task" edges to Task entities.
func (auo *AntUpdateOne) RemoveTask(t ...*Task) *AntUpdateOne {
	ids := make([]int64, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return auo.RemoveTaskIDs(ids...)
}

// Where appends a list predicates to the AntUpdate builder.
func (auo *AntUpdateOne) Where(ps ...predicate.Ant) *AntUpdateOne {
	auo.mutation.Where(ps...)
	return auo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (auo *AntUpdateOne) Select(field string, fields ...string) *AntUpdateOne {
	auo.fields = append([]string{field}, fields...)
	return auo
}

// Save executes the query and returns the updated Ant entity.
func (auo *AntUpdateOne) Save(ctx context.Context) (*Ant, error) {
	if err := auo.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, auo.sqlSave, auo.mutation, auo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (auo *AntUpdateOne) SaveX(ctx context.Context) *Ant {
	node, err := auo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (auo *AntUpdateOne) Exec(ctx context.Context) error {
	_, err := auo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (auo *AntUpdateOne) ExecX(ctx context.Context) {
	if err := auo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (auo *AntUpdateOne) defaults() error {
	if _, ok := auo.mutation.UpdatedAt(); !ok {
		if ant.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized ant.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := ant.UpdateDefaultUpdatedAt()
		auo.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (auo *AntUpdateOne) check() error {
	if v, ok := auo.mutation.ExtIP(); ok {
		if err := ant.ExtIPValidator(v.String()); err != nil {
			return &ValidationError{Name: "ext_ip", err: fmt.Errorf(`ent: validator failed for field "Ant.ext_ip": %w`, err)}
		}
	}
	if v, ok := auo.mutation.IntIP(); ok {
		if err := ant.IntIPValidator(v.String()); err != nil {
			return &ValidationError{Name: "int_ip", err: fmt.Errorf(`ent: validator failed for field "Ant.int_ip": %w`, err)}
		}
	}
	if v, ok := auo.mutation.Os(); ok {
		if err := ant.OsValidator(v); err != nil {
			return &ValidationError{Name: "os", err: fmt.Errorf(`ent: validator failed for field "Ant.os": %w`, err)}
		}
	}
	if v, ok := auo.mutation.OsMeta(); ok {
		if err := ant.OsMetaValidator(v); err != nil {
			return &ValidationError{Name: "os_meta", err: fmt.Errorf(`ent: validator failed for field "Ant.os_meta": %w`, err)}
		}
	}
	if v, ok := auo.mutation.Hostname(); ok {
		if err := ant.HostnameValidator(v); err != nil {
			return &ValidationError{Name: "hostname", err: fmt.Errorf(`ent: validator failed for field "Ant.hostname": %w`, err)}
		}
	}
	if v, ok := auo.mutation.Username(); ok {
		if err := ant.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "Ant.username": %w`, err)}
		}
	}
	if v, ok := auo.mutation.Domain(); ok {
		if err := ant.DomainValidator(v); err != nil {
			return &ValidationError{Name: "domain", err: fmt.Errorf(`ent: validator failed for field "Ant.domain": %w`, err)}
		}
	}
	if v, ok := auo.mutation.ProcessName(); ok {
		if err := ant.ProcessNameValidator(v); err != nil {
			return &ValidationError{Name: "process_name", err: fmt.Errorf(`ent: validator failed for field "Ant.process_name": %w`, err)}
		}
	}
	if v, ok := auo.mutation.Arch(); ok {
		if err := ant.ArchValidator(v); err != nil {
			return &ValidationError{Name: "arch", err: fmt.Errorf(`ent: validator failed for field "Ant.arch": %w`, err)}
		}
	}
	if v, ok := auo.mutation.Note(); ok {
		if err := ant.NoteValidator(v); err != nil {
			return &ValidationError{Name: "note", err: fmt.Errorf(`ent: validator failed for field "Ant.note": %w`, err)}
		}
	}
	if auo.mutation.ListenerCleared() && len(auo.mutation.ListenerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Ant.listener"`)
	}
	return nil
}

func (auo *AntUpdateOne) sqlSave(ctx context.Context) (_node *Ant, err error) {
	if err := auo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(ant.Table, ant.Columns, sqlgraph.NewFieldSpec(ant.FieldID, field.TypeUint32))
	id, ok := auo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Ant.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := auo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, ant.FieldID)
		for _, f := range fields {
			if !ant.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != ant.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := auo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := auo.mutation.UpdatedAt(); ok {
		_spec.SetField(ant.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := auo.mutation.DeletedAt(); ok {
		_spec.SetField(ant.FieldDeletedAt, field.TypeTime, value)
	}
	if auo.mutation.DeletedAtCleared() {
		_spec.ClearField(ant.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := auo.mutation.ExtIP(); ok {
		_spec.SetField(ant.FieldExtIP, field.TypeString, value)
	}
	if auo.mutation.ExtIPCleared() {
		_spec.ClearField(ant.FieldExtIP, field.TypeString)
	}
	if value, ok := auo.mutation.IntIP(); ok {
		_spec.SetField(ant.FieldIntIP, field.TypeString, value)
	}
	if auo.mutation.IntIPCleared() {
		_spec.ClearField(ant.FieldIntIP, field.TypeString)
	}
	if value, ok := auo.mutation.Os(); ok {
		_spec.SetField(ant.FieldOs, field.TypeEnum, value)
	}
	if value, ok := auo.mutation.OsMeta(); ok {
		_spec.SetField(ant.FieldOsMeta, field.TypeString, value)
	}
	if auo.mutation.OsMetaCleared() {
		_spec.ClearField(ant.FieldOsMeta, field.TypeString)
	}
	if value, ok := auo.mutation.Hostname(); ok {
		_spec.SetField(ant.FieldHostname, field.TypeString, value)
	}
	if auo.mutation.HostnameCleared() {
		_spec.ClearField(ant.FieldHostname, field.TypeString)
	}
	if value, ok := auo.mutation.Username(); ok {
		_spec.SetField(ant.FieldUsername, field.TypeString, value)
	}
	if auo.mutation.UsernameCleared() {
		_spec.ClearField(ant.FieldUsername, field.TypeString)
	}
	if value, ok := auo.mutation.Domain(); ok {
		_spec.SetField(ant.FieldDomain, field.TypeString, value)
	}
	if auo.mutation.DomainCleared() {
		_spec.ClearField(ant.FieldDomain, field.TypeString)
	}
	if value, ok := auo.mutation.Privileged(); ok {
		_spec.SetField(ant.FieldPrivileged, field.TypeBool, value)
	}
	if auo.mutation.PrivilegedCleared() {
		_spec.ClearField(ant.FieldPrivileged, field.TypeBool)
	}
	if value, ok := auo.mutation.ProcessName(); ok {
		_spec.SetField(ant.FieldProcessName, field.TypeString, value)
	}
	if auo.mutation.ProcessNameCleared() {
		_spec.ClearField(ant.FieldProcessName, field.TypeString)
	}
	if value, ok := auo.mutation.Pid(); ok {
		_spec.SetField(ant.FieldPid, field.TypeInt64, value)
	}
	if value, ok := auo.mutation.AddedPid(); ok {
		_spec.AddField(ant.FieldPid, field.TypeInt64, value)
	}
	if auo.mutation.PidCleared() {
		_spec.ClearField(ant.FieldPid, field.TypeInt64)
	}
	if value, ok := auo.mutation.Arch(); ok {
		_spec.SetField(ant.FieldArch, field.TypeEnum, value)
	}
	if value, ok := auo.mutation.Sleep(); ok {
		_spec.SetField(ant.FieldSleep, field.TypeUint32, value)
	}
	if value, ok := auo.mutation.AddedSleep(); ok {
		_spec.AddField(ant.FieldSleep, field.TypeUint32, value)
	}
	if value, ok := auo.mutation.Jitter(); ok {
		_spec.SetField(ant.FieldJitter, field.TypeUint8, value)
	}
	if value, ok := auo.mutation.AddedJitter(); ok {
		_spec.AddField(ant.FieldJitter, field.TypeUint8, value)
	}
	if value, ok := auo.mutation.First(); ok {
		_spec.SetField(ant.FieldFirst, field.TypeTime, value)
	}
	if value, ok := auo.mutation.Last(); ok {
		_spec.SetField(ant.FieldLast, field.TypeTime, value)
	}
	if value, ok := auo.mutation.Caps(); ok {
		_spec.SetField(ant.FieldCaps, field.TypeUint32, value)
	}
	if value, ok := auo.mutation.AddedCaps(); ok {
		_spec.AddField(ant.FieldCaps, field.TypeUint32, value)
	}
	if value, ok := auo.mutation.Note(); ok {
		_spec.SetField(ant.FieldNote, field.TypeString, value)
	}
	if auo.mutation.NoteCleared() {
		_spec.ClearField(ant.FieldNote, field.TypeString)
	}
	if value, ok := auo.mutation.Color(); ok {
		_spec.SetField(ant.FieldColor, field.TypeUint32, value)
	}
	if value, ok := auo.mutation.AddedColor(); ok {
		_spec.AddField(ant.FieldColor, field.TypeUint32, value)
	}
	if auo.mutation.ListenerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ant.ListenerTable,
			Columns: []string{ant.ListenerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(listener.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.ListenerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ant.ListenerTable,
			Columns: []string{ant.ListenerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(listener.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if auo.mutation.CommandCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ant.CommandTable,
			Columns: []string{ant.CommandColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(command.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.RemovedCommandIDs(); len(nodes) > 0 && !auo.mutation.CommandCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ant.CommandTable,
			Columns: []string{ant.CommandColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(command.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.CommandIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ant.CommandTable,
			Columns: []string{ant.CommandColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(command.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if auo.mutation.TaskCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ant.TaskTable,
			Columns: []string{ant.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.RemovedTaskIDs(); len(nodes) > 0 && !auo.mutation.TaskCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ant.TaskTable,
			Columns: []string{ant.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.TaskIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ant.TaskTable,
			Columns: []string{ant.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Ant{config: auo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, auo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ant.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	auo.mutation.done = true
	return _node, nil
}
