// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/PicoTools/pico-shared/shared"
	"github.com/PicoTools/pico/internal/ent/ant"
	"github.com/PicoTools/pico/internal/ent/command"
	"github.com/PicoTools/pico/internal/ent/listener"
	"github.com/PicoTools/pico/internal/ent/task"
	"github.com/PicoTools/pico/internal/types"
)

// AntCreate is the builder for creating a Ant entity.
type AntCreate struct {
	config
	mutation *AntMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (ac *AntCreate) SetCreatedAt(t time.Time) *AntCreate {
	ac.mutation.SetCreatedAt(t)
	return ac
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (ac *AntCreate) SetNillableCreatedAt(t *time.Time) *AntCreate {
	if t != nil {
		ac.SetCreatedAt(*t)
	}
	return ac
}

// SetUpdatedAt sets the "updated_at" field.
func (ac *AntCreate) SetUpdatedAt(t time.Time) *AntCreate {
	ac.mutation.SetUpdatedAt(t)
	return ac
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (ac *AntCreate) SetNillableUpdatedAt(t *time.Time) *AntCreate {
	if t != nil {
		ac.SetUpdatedAt(*t)
	}
	return ac
}

// SetDeletedAt sets the "deleted_at" field.
func (ac *AntCreate) SetDeletedAt(t time.Time) *AntCreate {
	ac.mutation.SetDeletedAt(t)
	return ac
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (ac *AntCreate) SetNillableDeletedAt(t *time.Time) *AntCreate {
	if t != nil {
		ac.SetDeletedAt(*t)
	}
	return ac
}

// SetListenerID sets the "listener_id" field.
func (ac *AntCreate) SetListenerID(i int64) *AntCreate {
	ac.mutation.SetListenerID(i)
	return ac
}

// SetExtIP sets the "ext_ip" field.
func (ac *AntCreate) SetExtIP(t types.Inet) *AntCreate {
	ac.mutation.SetExtIP(t)
	return ac
}

// SetNillableExtIP sets the "ext_ip" field if the given value is not nil.
func (ac *AntCreate) SetNillableExtIP(t *types.Inet) *AntCreate {
	if t != nil {
		ac.SetExtIP(*t)
	}
	return ac
}

// SetIntIP sets the "int_ip" field.
func (ac *AntCreate) SetIntIP(t types.Inet) *AntCreate {
	ac.mutation.SetIntIP(t)
	return ac
}

// SetNillableIntIP sets the "int_ip" field if the given value is not nil.
func (ac *AntCreate) SetNillableIntIP(t *types.Inet) *AntCreate {
	if t != nil {
		ac.SetIntIP(*t)
	}
	return ac
}

// SetOs sets the "os" field.
func (ac *AntCreate) SetOs(so shared.AntOs) *AntCreate {
	ac.mutation.SetOs(so)
	return ac
}

// SetOsMeta sets the "os_meta" field.
func (ac *AntCreate) SetOsMeta(s string) *AntCreate {
	ac.mutation.SetOsMeta(s)
	return ac
}

// SetNillableOsMeta sets the "os_meta" field if the given value is not nil.
func (ac *AntCreate) SetNillableOsMeta(s *string) *AntCreate {
	if s != nil {
		ac.SetOsMeta(*s)
	}
	return ac
}

// SetHostname sets the "hostname" field.
func (ac *AntCreate) SetHostname(s string) *AntCreate {
	ac.mutation.SetHostname(s)
	return ac
}

// SetNillableHostname sets the "hostname" field if the given value is not nil.
func (ac *AntCreate) SetNillableHostname(s *string) *AntCreate {
	if s != nil {
		ac.SetHostname(*s)
	}
	return ac
}

// SetUsername sets the "username" field.
func (ac *AntCreate) SetUsername(s string) *AntCreate {
	ac.mutation.SetUsername(s)
	return ac
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (ac *AntCreate) SetNillableUsername(s *string) *AntCreate {
	if s != nil {
		ac.SetUsername(*s)
	}
	return ac
}

// SetDomain sets the "domain" field.
func (ac *AntCreate) SetDomain(s string) *AntCreate {
	ac.mutation.SetDomain(s)
	return ac
}

// SetNillableDomain sets the "domain" field if the given value is not nil.
func (ac *AntCreate) SetNillableDomain(s *string) *AntCreate {
	if s != nil {
		ac.SetDomain(*s)
	}
	return ac
}

// SetPrivileged sets the "privileged" field.
func (ac *AntCreate) SetPrivileged(b bool) *AntCreate {
	ac.mutation.SetPrivileged(b)
	return ac
}

// SetNillablePrivileged sets the "privileged" field if the given value is not nil.
func (ac *AntCreate) SetNillablePrivileged(b *bool) *AntCreate {
	if b != nil {
		ac.SetPrivileged(*b)
	}
	return ac
}

// SetProcessName sets the "process_name" field.
func (ac *AntCreate) SetProcessName(s string) *AntCreate {
	ac.mutation.SetProcessName(s)
	return ac
}

// SetNillableProcessName sets the "process_name" field if the given value is not nil.
func (ac *AntCreate) SetNillableProcessName(s *string) *AntCreate {
	if s != nil {
		ac.SetProcessName(*s)
	}
	return ac
}

// SetPid sets the "pid" field.
func (ac *AntCreate) SetPid(i int64) *AntCreate {
	ac.mutation.SetPid(i)
	return ac
}

// SetNillablePid sets the "pid" field if the given value is not nil.
func (ac *AntCreate) SetNillablePid(i *int64) *AntCreate {
	if i != nil {
		ac.SetPid(*i)
	}
	return ac
}

// SetArch sets the "arch" field.
func (ac *AntCreate) SetArch(sa shared.AntArch) *AntCreate {
	ac.mutation.SetArch(sa)
	return ac
}

// SetSleep sets the "sleep" field.
func (ac *AntCreate) SetSleep(u uint32) *AntCreate {
	ac.mutation.SetSleep(u)
	return ac
}

// SetJitter sets the "jitter" field.
func (ac *AntCreate) SetJitter(u uint8) *AntCreate {
	ac.mutation.SetJitter(u)
	return ac
}

// SetFirst sets the "first" field.
func (ac *AntCreate) SetFirst(t time.Time) *AntCreate {
	ac.mutation.SetFirst(t)
	return ac
}

// SetNillableFirst sets the "first" field if the given value is not nil.
func (ac *AntCreate) SetNillableFirst(t *time.Time) *AntCreate {
	if t != nil {
		ac.SetFirst(*t)
	}
	return ac
}

// SetLast sets the "last" field.
func (ac *AntCreate) SetLast(t time.Time) *AntCreate {
	ac.mutation.SetLast(t)
	return ac
}

// SetNillableLast sets the "last" field if the given value is not nil.
func (ac *AntCreate) SetNillableLast(t *time.Time) *AntCreate {
	if t != nil {
		ac.SetLast(*t)
	}
	return ac
}

// SetCaps sets the "caps" field.
func (ac *AntCreate) SetCaps(u uint32) *AntCreate {
	ac.mutation.SetCaps(u)
	return ac
}

// SetNote sets the "note" field.
func (ac *AntCreate) SetNote(s string) *AntCreate {
	ac.mutation.SetNote(s)
	return ac
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (ac *AntCreate) SetNillableNote(s *string) *AntCreate {
	if s != nil {
		ac.SetNote(*s)
	}
	return ac
}

// SetColor sets the "color" field.
func (ac *AntCreate) SetColor(u uint32) *AntCreate {
	ac.mutation.SetColor(u)
	return ac
}

// SetNillableColor sets the "color" field if the given value is not nil.
func (ac *AntCreate) SetNillableColor(u *uint32) *AntCreate {
	if u != nil {
		ac.SetColor(*u)
	}
	return ac
}

// SetID sets the "id" field.
func (ac *AntCreate) SetID(u uint32) *AntCreate {
	ac.mutation.SetID(u)
	return ac
}

// SetListener sets the "listener" edge to the Listener entity.
func (ac *AntCreate) SetListener(l *Listener) *AntCreate {
	return ac.SetListenerID(l.ID)
}

// AddCommandIDs adds the "command" edge to the Command entity by IDs.
func (ac *AntCreate) AddCommandIDs(ids ...int64) *AntCreate {
	ac.mutation.AddCommandIDs(ids...)
	return ac
}

// AddCommand adds the "command" edges to the Command entity.
func (ac *AntCreate) AddCommand(c ...*Command) *AntCreate {
	ids := make([]int64, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return ac.AddCommandIDs(ids...)
}

// AddTaskIDs adds the "task" edge to the Task entity by IDs.
func (ac *AntCreate) AddTaskIDs(ids ...int64) *AntCreate {
	ac.mutation.AddTaskIDs(ids...)
	return ac
}

// AddTask adds the "task" edges to the Task entity.
func (ac *AntCreate) AddTask(t ...*Task) *AntCreate {
	ids := make([]int64, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return ac.AddTaskIDs(ids...)
}

// Mutation returns the AntMutation object of the builder.
func (ac *AntCreate) Mutation() *AntMutation {
	return ac.mutation
}

// Save creates the Ant in the database.
func (ac *AntCreate) Save(ctx context.Context) (*Ant, error) {
	if err := ac.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, ac.sqlSave, ac.mutation, ac.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ac *AntCreate) SaveX(ctx context.Context) *Ant {
	v, err := ac.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ac *AntCreate) Exec(ctx context.Context) error {
	_, err := ac.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ac *AntCreate) ExecX(ctx context.Context) {
	if err := ac.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ac *AntCreate) defaults() error {
	if _, ok := ac.mutation.CreatedAt(); !ok {
		if ant.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized ant.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := ant.DefaultCreatedAt()
		ac.mutation.SetCreatedAt(v)
	}
	if _, ok := ac.mutation.UpdatedAt(); !ok {
		if ant.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized ant.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := ant.DefaultUpdatedAt()
		ac.mutation.SetUpdatedAt(v)
	}
	if _, ok := ac.mutation.First(); !ok {
		if ant.DefaultFirst == nil {
			return fmt.Errorf("ent: uninitialized ant.DefaultFirst (forgotten import ent/runtime?)")
		}
		v := ant.DefaultFirst()
		ac.mutation.SetFirst(v)
	}
	if _, ok := ac.mutation.Last(); !ok {
		if ant.DefaultLast == nil {
			return fmt.Errorf("ent: uninitialized ant.DefaultLast (forgotten import ent/runtime?)")
		}
		v := ant.DefaultLast()
		ac.mutation.SetLast(v)
	}
	if _, ok := ac.mutation.Color(); !ok {
		v := ant.DefaultColor
		ac.mutation.SetColor(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (ac *AntCreate) check() error {
	if _, ok := ac.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Ant.created_at"`)}
	}
	if _, ok := ac.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Ant.updated_at"`)}
	}
	if _, ok := ac.mutation.ListenerID(); !ok {
		return &ValidationError{Name: "listener_id", err: errors.New(`ent: missing required field "Ant.listener_id"`)}
	}
	if v, ok := ac.mutation.ExtIP(); ok {
		if err := ant.ExtIPValidator(v.String()); err != nil {
			return &ValidationError{Name: "ext_ip", err: fmt.Errorf(`ent: validator failed for field "Ant.ext_ip": %w`, err)}
		}
	}
	if v, ok := ac.mutation.IntIP(); ok {
		if err := ant.IntIPValidator(v.String()); err != nil {
			return &ValidationError{Name: "int_ip", err: fmt.Errorf(`ent: validator failed for field "Ant.int_ip": %w`, err)}
		}
	}
	if _, ok := ac.mutation.Os(); !ok {
		return &ValidationError{Name: "os", err: errors.New(`ent: missing required field "Ant.os"`)}
	}
	if v, ok := ac.mutation.Os(); ok {
		if err := ant.OsValidator(v); err != nil {
			return &ValidationError{Name: "os", err: fmt.Errorf(`ent: validator failed for field "Ant.os": %w`, err)}
		}
	}
	if v, ok := ac.mutation.OsMeta(); ok {
		if err := ant.OsMetaValidator(v); err != nil {
			return &ValidationError{Name: "os_meta", err: fmt.Errorf(`ent: validator failed for field "Ant.os_meta": %w`, err)}
		}
	}
	if v, ok := ac.mutation.Hostname(); ok {
		if err := ant.HostnameValidator(v); err != nil {
			return &ValidationError{Name: "hostname", err: fmt.Errorf(`ent: validator failed for field "Ant.hostname": %w`, err)}
		}
	}
	if v, ok := ac.mutation.Username(); ok {
		if err := ant.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "Ant.username": %w`, err)}
		}
	}
	if v, ok := ac.mutation.Domain(); ok {
		if err := ant.DomainValidator(v); err != nil {
			return &ValidationError{Name: "domain", err: fmt.Errorf(`ent: validator failed for field "Ant.domain": %w`, err)}
		}
	}
	if v, ok := ac.mutation.ProcessName(); ok {
		if err := ant.ProcessNameValidator(v); err != nil {
			return &ValidationError{Name: "process_name", err: fmt.Errorf(`ent: validator failed for field "Ant.process_name": %w`, err)}
		}
	}
	if _, ok := ac.mutation.Arch(); !ok {
		return &ValidationError{Name: "arch", err: errors.New(`ent: missing required field "Ant.arch"`)}
	}
	if v, ok := ac.mutation.Arch(); ok {
		if err := ant.ArchValidator(v); err != nil {
			return &ValidationError{Name: "arch", err: fmt.Errorf(`ent: validator failed for field "Ant.arch": %w`, err)}
		}
	}
	if _, ok := ac.mutation.Sleep(); !ok {
		return &ValidationError{Name: "sleep", err: errors.New(`ent: missing required field "Ant.sleep"`)}
	}
	if _, ok := ac.mutation.Jitter(); !ok {
		return &ValidationError{Name: "jitter", err: errors.New(`ent: missing required field "Ant.jitter"`)}
	}
	if _, ok := ac.mutation.First(); !ok {
		return &ValidationError{Name: "first", err: errors.New(`ent: missing required field "Ant.first"`)}
	}
	if _, ok := ac.mutation.Last(); !ok {
		return &ValidationError{Name: "last", err: errors.New(`ent: missing required field "Ant.last"`)}
	}
	if _, ok := ac.mutation.Caps(); !ok {
		return &ValidationError{Name: "caps", err: errors.New(`ent: missing required field "Ant.caps"`)}
	}
	if v, ok := ac.mutation.Note(); ok {
		if err := ant.NoteValidator(v); err != nil {
			return &ValidationError{Name: "note", err: fmt.Errorf(`ent: validator failed for field "Ant.note": %w`, err)}
		}
	}
	if _, ok := ac.mutation.Color(); !ok {
		return &ValidationError{Name: "color", err: errors.New(`ent: missing required field "Ant.color"`)}
	}
	if len(ac.mutation.ListenerIDs()) == 0 {
		return &ValidationError{Name: "listener", err: errors.New(`ent: missing required edge "Ant.listener"`)}
	}
	return nil
}

func (ac *AntCreate) sqlSave(ctx context.Context) (*Ant, error) {
	if err := ac.check(); err != nil {
		return nil, err
	}
	_node, _spec := ac.createSpec()
	if err := sqlgraph.CreateNode(ctx, ac.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint32(id)
	}
	ac.mutation.id = &_node.ID
	ac.mutation.done = true
	return _node, nil
}

func (ac *AntCreate) createSpec() (*Ant, *sqlgraph.CreateSpec) {
	var (
		_node = &Ant{config: ac.config}
		_spec = sqlgraph.NewCreateSpec(ant.Table, sqlgraph.NewFieldSpec(ant.FieldID, field.TypeUint32))
	)
	if id, ok := ac.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := ac.mutation.CreatedAt(); ok {
		_spec.SetField(ant.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := ac.mutation.UpdatedAt(); ok {
		_spec.SetField(ant.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := ac.mutation.DeletedAt(); ok {
		_spec.SetField(ant.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = value
	}
	if value, ok := ac.mutation.ExtIP(); ok {
		_spec.SetField(ant.FieldExtIP, field.TypeString, value)
		_node.ExtIP = value
	}
	if value, ok := ac.mutation.IntIP(); ok {
		_spec.SetField(ant.FieldIntIP, field.TypeString, value)
		_node.IntIP = value
	}
	if value, ok := ac.mutation.Os(); ok {
		_spec.SetField(ant.FieldOs, field.TypeEnum, value)
		_node.Os = value
	}
	if value, ok := ac.mutation.OsMeta(); ok {
		_spec.SetField(ant.FieldOsMeta, field.TypeString, value)
		_node.OsMeta = value
	}
	if value, ok := ac.mutation.Hostname(); ok {
		_spec.SetField(ant.FieldHostname, field.TypeString, value)
		_node.Hostname = value
	}
	if value, ok := ac.mutation.Username(); ok {
		_spec.SetField(ant.FieldUsername, field.TypeString, value)
		_node.Username = value
	}
	if value, ok := ac.mutation.Domain(); ok {
		_spec.SetField(ant.FieldDomain, field.TypeString, value)
		_node.Domain = value
	}
	if value, ok := ac.mutation.Privileged(); ok {
		_spec.SetField(ant.FieldPrivileged, field.TypeBool, value)
		_node.Privileged = value
	}
	if value, ok := ac.mutation.ProcessName(); ok {
		_spec.SetField(ant.FieldProcessName, field.TypeString, value)
		_node.ProcessName = value
	}
	if value, ok := ac.mutation.Pid(); ok {
		_spec.SetField(ant.FieldPid, field.TypeInt64, value)
		_node.Pid = value
	}
	if value, ok := ac.mutation.Arch(); ok {
		_spec.SetField(ant.FieldArch, field.TypeEnum, value)
		_node.Arch = value
	}
	if value, ok := ac.mutation.Sleep(); ok {
		_spec.SetField(ant.FieldSleep, field.TypeUint32, value)
		_node.Sleep = value
	}
	if value, ok := ac.mutation.Jitter(); ok {
		_spec.SetField(ant.FieldJitter, field.TypeUint8, value)
		_node.Jitter = value
	}
	if value, ok := ac.mutation.First(); ok {
		_spec.SetField(ant.FieldFirst, field.TypeTime, value)
		_node.First = value
	}
	if value, ok := ac.mutation.Last(); ok {
		_spec.SetField(ant.FieldLast, field.TypeTime, value)
		_node.Last = value
	}
	if value, ok := ac.mutation.Caps(); ok {
		_spec.SetField(ant.FieldCaps, field.TypeUint32, value)
		_node.Caps = value
	}
	if value, ok := ac.mutation.Note(); ok {
		_spec.SetField(ant.FieldNote, field.TypeString, value)
		_node.Note = value
	}
	if value, ok := ac.mutation.Color(); ok {
		_spec.SetField(ant.FieldColor, field.TypeUint32, value)
		_node.Color = value
	}
	if nodes := ac.mutation.ListenerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ant.ListenerTable,
			Columns: []string{ant.ListenerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(listener.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ListenerID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := ac.mutation.CommandIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ant.CommandTable,
			Columns: []string{ant.CommandColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(command.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := ac.mutation.TaskIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ant.TaskTable,
			Columns: []string{ant.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AntCreateBulk is the builder for creating many Ant entities in bulk.
type AntCreateBulk struct {
	config
	err      error
	builders []*AntCreate
}

// Save creates the Ant entities in the database.
func (acb *AntCreateBulk) Save(ctx context.Context) ([]*Ant, error) {
	if acb.err != nil {
		return nil, acb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(acb.builders))
	nodes := make([]*Ant, len(acb.builders))
	mutators := make([]Mutator, len(acb.builders))
	for i := range acb.builders {
		func(i int, root context.Context) {
			builder := acb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AntMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, acb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, acb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint32(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, acb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (acb *AntCreateBulk) SaveX(ctx context.Context) []*Ant {
	v, err := acb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (acb *AntCreateBulk) Exec(ctx context.Context) error {
	_, err := acb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (acb *AntCreateBulk) ExecX(ctx context.Context) {
	if err := acb.Exec(ctx); err != nil {
		panic(err)
	}
}
