// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/PicoTools/pico/internal/ent/ant"
	"github.com/PicoTools/pico/internal/ent/command"
	"github.com/PicoTools/pico/internal/ent/message"
	"github.com/PicoTools/pico/internal/ent/operator"
	"github.com/PicoTools/pico/internal/ent/task"
)

// CommandCreate is the builder for creating a Command entity.
type CommandCreate struct {
	config
	mutation *CommandMutation
	hooks    []Hook
}

// SetAntID sets the "ant_id" field.
func (cc *CommandCreate) SetAntID(u uint32) *CommandCreate {
	cc.mutation.SetAntID(u)
	return cc
}

// SetCmd sets the "cmd" field.
func (cc *CommandCreate) SetCmd(s string) *CommandCreate {
	cc.mutation.SetCmd(s)
	return cc
}

// SetVisible sets the "visible" field.
func (cc *CommandCreate) SetVisible(b bool) *CommandCreate {
	cc.mutation.SetVisible(b)
	return cc
}

// SetAuthorID sets the "author_id" field.
func (cc *CommandCreate) SetAuthorID(i int64) *CommandCreate {
	cc.mutation.SetAuthorID(i)
	return cc
}

// SetCreatedAt sets the "created_at" field.
func (cc *CommandCreate) SetCreatedAt(t time.Time) *CommandCreate {
	cc.mutation.SetCreatedAt(t)
	return cc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (cc *CommandCreate) SetNillableCreatedAt(t *time.Time) *CommandCreate {
	if t != nil {
		cc.SetCreatedAt(*t)
	}
	return cc
}

// SetClosedAt sets the "closed_at" field.
func (cc *CommandCreate) SetClosedAt(t time.Time) *CommandCreate {
	cc.mutation.SetClosedAt(t)
	return cc
}

// SetNillableClosedAt sets the "closed_at" field if the given value is not nil.
func (cc *CommandCreate) SetNillableClosedAt(t *time.Time) *CommandCreate {
	if t != nil {
		cc.SetClosedAt(*t)
	}
	return cc
}

// SetID sets the "id" field.
func (cc *CommandCreate) SetID(i int64) *CommandCreate {
	cc.mutation.SetID(i)
	return cc
}

// SetAnt sets the "ant" edge to the Ant entity.
func (cc *CommandCreate) SetAnt(a *Ant) *CommandCreate {
	return cc.SetAntID(a.ID)
}

// SetOperatorID sets the "operator" edge to the Operator entity by ID.
func (cc *CommandCreate) SetOperatorID(id int64) *CommandCreate {
	cc.mutation.SetOperatorID(id)
	return cc
}

// SetOperator sets the "operator" edge to the Operator entity.
func (cc *CommandCreate) SetOperator(o *Operator) *CommandCreate {
	return cc.SetOperatorID(o.ID)
}

// AddMessageIDs adds the "message" edge to the Message entity by IDs.
func (cc *CommandCreate) AddMessageIDs(ids ...int) *CommandCreate {
	cc.mutation.AddMessageIDs(ids...)
	return cc
}

// AddMessage adds the "message" edges to the Message entity.
func (cc *CommandCreate) AddMessage(m ...*Message) *CommandCreate {
	ids := make([]int, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return cc.AddMessageIDs(ids...)
}

// AddTaskIDs adds the "task" edge to the Task entity by IDs.
func (cc *CommandCreate) AddTaskIDs(ids ...int64) *CommandCreate {
	cc.mutation.AddTaskIDs(ids...)
	return cc
}

// AddTask adds the "task" edges to the Task entity.
func (cc *CommandCreate) AddTask(t ...*Task) *CommandCreate {
	ids := make([]int64, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return cc.AddTaskIDs(ids...)
}

// Mutation returns the CommandMutation object of the builder.
func (cc *CommandCreate) Mutation() *CommandMutation {
	return cc.mutation
}

// Save creates the Command in the database.
func (cc *CommandCreate) Save(ctx context.Context) (*Command, error) {
	cc.defaults()
	return withHooks(ctx, cc.sqlSave, cc.mutation, cc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (cc *CommandCreate) SaveX(ctx context.Context) *Command {
	v, err := cc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (cc *CommandCreate) Exec(ctx context.Context) error {
	_, err := cc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cc *CommandCreate) ExecX(ctx context.Context) {
	if err := cc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (cc *CommandCreate) defaults() {
	if _, ok := cc.mutation.CreatedAt(); !ok {
		v := command.DefaultCreatedAt()
		cc.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cc *CommandCreate) check() error {
	if _, ok := cc.mutation.AntID(); !ok {
		return &ValidationError{Name: "ant_id", err: errors.New(`ent: missing required field "Command.ant_id"`)}
	}
	if _, ok := cc.mutation.Cmd(); !ok {
		return &ValidationError{Name: "cmd", err: errors.New(`ent: missing required field "Command.cmd"`)}
	}
	if v, ok := cc.mutation.Cmd(); ok {
		if err := command.CmdValidator(v); err != nil {
			return &ValidationError{Name: "cmd", err: fmt.Errorf(`ent: validator failed for field "Command.cmd": %w`, err)}
		}
	}
	if _, ok := cc.mutation.Visible(); !ok {
		return &ValidationError{Name: "visible", err: errors.New(`ent: missing required field "Command.visible"`)}
	}
	if _, ok := cc.mutation.AuthorID(); !ok {
		return &ValidationError{Name: "author_id", err: errors.New(`ent: missing required field "Command.author_id"`)}
	}
	if _, ok := cc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Command.created_at"`)}
	}
	if len(cc.mutation.AntIDs()) == 0 {
		return &ValidationError{Name: "ant", err: errors.New(`ent: missing required edge "Command.ant"`)}
	}
	if len(cc.mutation.OperatorIDs()) == 0 {
		return &ValidationError{Name: "operator", err: errors.New(`ent: missing required edge "Command.operator"`)}
	}
	return nil
}

func (cc *CommandCreate) sqlSave(ctx context.Context) (*Command, error) {
	if err := cc.check(); err != nil {
		return nil, err
	}
	_node, _spec := cc.createSpec()
	if err := sqlgraph.CreateNode(ctx, cc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	cc.mutation.id = &_node.ID
	cc.mutation.done = true
	return _node, nil
}

func (cc *CommandCreate) createSpec() (*Command, *sqlgraph.CreateSpec) {
	var (
		_node = &Command{config: cc.config}
		_spec = sqlgraph.NewCreateSpec(command.Table, sqlgraph.NewFieldSpec(command.FieldID, field.TypeInt64))
	)
	if id, ok := cc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := cc.mutation.Cmd(); ok {
		_spec.SetField(command.FieldCmd, field.TypeString, value)
		_node.Cmd = value
	}
	if value, ok := cc.mutation.Visible(); ok {
		_spec.SetField(command.FieldVisible, field.TypeBool, value)
		_node.Visible = value
	}
	if value, ok := cc.mutation.CreatedAt(); ok {
		_spec.SetField(command.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := cc.mutation.ClosedAt(); ok {
		_spec.SetField(command.FieldClosedAt, field.TypeTime, value)
		_node.ClosedAt = value
	}
	if nodes := cc.mutation.AntIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   command.AntTable,
			Columns: []string{command.AntColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ant.FieldID, field.TypeUint32),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AntID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := cc.mutation.OperatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   command.OperatorTable,
			Columns: []string{command.OperatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(operator.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AuthorID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := cc.mutation.MessageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   command.MessageTable,
			Columns: []string{command.MessageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := cc.mutation.TaskIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   command.TaskTable,
			Columns: []string{command.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// CommandCreateBulk is the builder for creating many Command entities in bulk.
type CommandCreateBulk struct {
	config
	err      error
	builders []*CommandCreate
}

// Save creates the Command entities in the database.
func (ccb *CommandCreateBulk) Save(ctx context.Context) ([]*Command, error) {
	if ccb.err != nil {
		return nil, ccb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ccb.builders))
	nodes := make([]*Command, len(ccb.builders))
	mutators := make([]Mutator, len(ccb.builders))
	for i := range ccb.builders {
		func(i int, root context.Context) {
			builder := ccb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CommandMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ccb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ccb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ccb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ccb *CommandCreateBulk) SaveX(ctx context.Context) []*Command {
	v, err := ccb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ccb *CommandCreateBulk) Exec(ctx context.Context) error {
	_, err := ccb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ccb *CommandCreateBulk) ExecX(ctx context.Context) {
	if err := ccb.Exec(ctx); err != nil {
		panic(err)
	}
}
